dataset_path: /ivi/ilps/datasets/baidu_ultr/
output_path: /ivi/ilps/personal/phager/baidu_ultr/
part: 0

### Define columns to load ###
query_columns: []
document_columns:
  - pos
  - url_md5
  - click
  - displayed_count

### Post-processing while merging ###
document_pipeline:
  _target_: src.processing.Pipeline
  steps:
    - _target_: src.processing.EncodeLabel
      column: url_md5
    - _target_: src.processing.EncodeLabel
      column: qid
    - _target_: src.processing.RenameColumns
      column_mapping:
        qid: query_id
        url_md5: doc_id
        pos: position

query_pipeline:
  _target_: src.processing.Pipeline
  steps: [ ]

delete_parts_after_merge: True

defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    mem_gb: 4
    cpus_per_task: 4
    array_parallelism: 10
    partition: cpu



